apiVersion: v1
kind: Service
metadata:
  name: kh-backend
  labels:
    app: kh-backend
spec:
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: kh-backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kh-backend
spec:
  selector:
    matchLabels:
      app: kh-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: kh-backend
    spec:
      containers:
        - name: kh-backend
          image: knighthacks2021.azurecr.io/backend
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 50m
            limits:
              cpu: 100m
          envFrom:
          - configMapRef:
              name: kh-backend-config
          - secretRef:
              name: kh-backend-secret
          - secretRef:
              name: kh-notionjob-secret
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kh-backend
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kh-backend
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
